# Generated by Django 5.0.2 on 2025-02-14 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('mid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField()),
                ('wind_speed', models.FloatField()),
                ('humidity', models.IntegerField()),
                ('temperature', models.IntegerField()),
                ('wind_direction', models.IntegerField()),
                ('prediction', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nodeid', models.TextField()),
                ('dcvoltage', models.TextField()),
                ('dccurrent', models.TextField()),
                ('acvoltage', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
